[package]
name = "cherri/emberfalle"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
replicacontroller = "etheroit/replicacontroller@1.0.0"
table-util = "sleitnick/table-util@1.2.1"
signal = "sleitnick/signal@2.0.1"

[server-dependencies]
replicaservice = "brittonfischer/replicaservice@0.1.0"
profileservice = "grilme99/profileservice@1.0.0"